import type { ResumeTemplateFieldSchema } from '../types/template-schema.types';
import { RESUME_LIMITS } from './resume-limits';

export const RESUME_ALLOWED_FIELD_KEYS = new Set([
  'personal.fullName', 'personal.jobTitle', 'personal.email', 'personal.phone',
  'personal.location', 'personal.website', 'personal.linkedin', 'personal.github',
  'personal.photoFileId', 'personal.drivingLicense', 'summary',
  'experience.company', 'experience.position', 'experience.employmentType',
  'experience.location', 'experience.startDate', 'experience.endDate',
  'experience.isCurrent',
  'experience.description', 'experience.bullets',
  'education.institution', 'education.degree', 'education.fieldOfStudy',
  'education.cgpa', 'education.location', 'education.startDate',
  'education.endDate', 'education.isCurrent', 'education.achievements',
  'education.description',
  'skills',
  'projects.name', 'projects.role', 'projects.url', 'projects.startDate',
  'projects.endDate', 'projects.isCurrent', 'projects.description',
  'projects.bullets', 'projects.technologies',
  'languages.name', 'languages.proficiency',
  'certifications.name', 'certifications.issuer', 'certifications.issueDate',
  'certifications.expiryDate', 'certifications.doesNotExpire',
  'certifications.credentialId', 'certifications.credentialUrl',
  'references.name', 'references.title', 'references.company',
  'references.email', 'references.phone',
]);

export const DEFAULT_RESUME_FIELD_SCHEMA: ResumeTemplateFieldSchema = {
  version: 1,
  sections: [
    {
      key: 'personal',
      label: 'Personal information',
      enabled: true,
      required: true,
      order: 0,
      zone: 'header',
      fields: [
        { key: 'personal.fullName', label: 'Full name', type: 'text', enabled: true, required: true, maxLength: RESUME_LIMITS.fullName },
        { key: 'personal.jobTitle', label: 'Job title', type: 'text', enabled: true, maxLength: RESUME_LIMITS.jobTitle },
        { key: 'personal.email', label: 'Email', type: 'email', enabled: true, maxLength: RESUME_LIMITS.email },
        { key: 'personal.phone', label: 'Phone', type: 'phone', enabled: true, maxLength: RESUME_LIMITS.phone },
        { key: 'personal.location', label: 'Location', type: 'text', enabled: true, maxLength: RESUME_LIMITS.location },
        { key: 'personal.website', label: 'Website', type: 'url', enabled: true, maxLength: RESUME_LIMITS.url },
        { key: 'personal.linkedin', label: 'LinkedIn', type: 'url', enabled: true, maxLength: RESUME_LIMITS.url },
        { key: 'personal.github', label: 'GitHub', type: 'url', enabled: true, maxLength: RESUME_LIMITS.url },
        { key: 'personal.photoFileId', label: 'Profile photo', type: 'image', enabled: true },
        { key: 'personal.drivingLicense', label: 'Driving license', type: 'tags', enabled: true, maxItems: RESUME_LIMITS.drivingLicenseItems, maxLength: 40 },
      ],
    },
    {
      key: 'summary',
      label: 'Professional summary',
      enabled: true,
      order: 10,
      zone: 'main',
      fields: [
        { key: 'summary', label: 'Summary', type: 'textarea', enabled: true, maxLength: RESUME_LIMITS.summary, aiAssist: 'summary-suggestions' },
      ],
    },
    {
      key: 'experience',
      label: 'Experience',
      enabled: true,
      order: 20,
      zone: 'main',
      maxItems: RESUME_LIMITS.experienceItems,
      fields: [
        { key: 'experience.company', label: 'Company', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'experience.position', label: 'Position', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'experience.employmentType', label: 'Employment type', type: 'select', enabled: true, options: ['Full-time', 'Part-time', 'Contract', 'Freelance', 'Internship', 'Temporary', 'Apprenticeship'] },
        { key: 'experience.location', label: 'Location', type: 'text', enabled: true, maxLength: RESUME_LIMITS.location },
        { key: 'experience.startDate', label: 'Start date', type: 'date', enabled: true },
        { key: 'experience.endDate', label: 'End date', type: 'date', enabled: true },
        { key: 'experience.isCurrent', label: 'Currently working here', type: 'boolean', enabled: true },
        { key: 'experience.description', label: 'Description', type: 'textarea', enabled: true, maxLength: RESUME_LIMITS.description, aiAssist: 'description-suggestions' },
        { key: 'experience.bullets', label: 'Highlights', type: 'repeatable', enabled: true, maxItems: RESUME_LIMITS.bulletsPerItem, maxLength: RESUME_LIMITS.bullet, aiAssist: 'highlight-suggestions' },
      ],
    },
    {
      key: 'education',
      label: 'Education',
      enabled: true,
      order: 30,
      zone: 'main',
      maxItems: RESUME_LIMITS.educationItems,
      fields: [
        { key: 'education.institution', label: 'Institution', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'education.degree', label: 'Degree', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'education.fieldOfStudy', label: 'Field of study', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'education.cgpa', label: 'CGPA / GPA', type: 'text', enabled: true, maxLength: 40 },
        { key: 'education.location', label: 'Location', type: 'text', enabled: true, maxLength: RESUME_LIMITS.location },
        { key: 'education.startDate', label: 'Start date', type: 'date', enabled: true },
        { key: 'education.endDate', label: 'End date', type: 'date', enabled: true },
        { key: 'education.isCurrent', label: 'Currently studying here', type: 'boolean', enabled: true },
        { key: 'education.achievements', label: 'Achievements', type: 'repeatable', enabled: true, maxItems: RESUME_LIMITS.bulletsPerItem, maxLength: RESUME_LIMITS.bullet },
        { key: 'education.description', label: 'Description', type: 'textarea', enabled: true, maxLength: RESUME_LIMITS.description },
      ],
    },
    {
      key: 'skills',
      label: 'Skills',
      enabled: true,
      order: 40,
      zone: 'sidebar',
      maxItems: RESUME_LIMITS.skillItems,
      fields: [{ key: 'skills', label: 'Skills', type: 'tags', enabled: true, maxItems: RESUME_LIMITS.skillItems, maxLength: RESUME_LIMITS.shortText, aiAssist: 'technical-skill-suggestions' }],
    },
    {
      key: 'projects',
      label: 'Projects',
      enabled: true,
      order: 50,
      zone: 'main',
      maxItems: RESUME_LIMITS.projectItems,
      fields: [
        { key: 'projects.name', label: 'Project name', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'projects.role', label: 'Role', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'projects.url', label: 'Project URL', type: 'url', enabled: true, maxLength: RESUME_LIMITS.url },
        { key: 'projects.startDate', label: 'Start date', type: 'date', enabled: true },
        { key: 'projects.endDate', label: 'End date', type: 'date', enabled: true },
        { key: 'projects.isCurrent', label: 'Ongoing project', type: 'boolean', enabled: true },
        { key: 'projects.description', label: 'Description', type: 'textarea', enabled: true, maxLength: RESUME_LIMITS.description, aiAssist: 'description-suggestions' },
        { key: 'projects.bullets', label: 'Highlights', type: 'repeatable', enabled: true, maxItems: RESUME_LIMITS.bulletsPerItem, maxLength: RESUME_LIMITS.bullet, aiAssist: 'highlight-suggestions' },
        { key: 'projects.technologies', label: 'Technologies', type: 'tags', enabled: true, maxItems: 30, maxLength: RESUME_LIMITS.shortText },
      ],
    },
    {
      key: 'languages',
      label: 'Languages',
      enabled: true,
      order: 60,
      zone: 'sidebar',
      maxItems: RESUME_LIMITS.languageItems,
      fields: [
        { key: 'languages.name', label: 'Language', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'languages.proficiency', label: 'Proficiency', type: 'select', enabled: true, options: ['Native', 'Fluent', 'Professional', 'Intermediate', 'Basic'] },
      ],
    },
    {
      key: 'certifications',
      label: 'Certifications',
      enabled: true,
      order: 70,
      zone: 'main',
      maxItems: RESUME_LIMITS.certificationItems,
      fields: [
        { key: 'certifications.name', label: 'Certification', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'certifications.issuer', label: 'Issuer', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'certifications.issueDate', label: 'Issue date', type: 'date', enabled: true },
        { key: 'certifications.expiryDate', label: 'Expiry date', type: 'date', enabled: true },
        { key: 'certifications.doesNotExpire', label: 'Does not expire', type: 'boolean', enabled: true },
        { key: 'certifications.credentialId', label: 'Credential ID', type: 'text', enabled: true, maxLength: 160 },
        { key: 'certifications.credentialUrl', label: 'Credential URL', type: 'url', enabled: true, maxLength: RESUME_LIMITS.url },
      ],
    },
    {
      key: 'references',
      label: 'References',
      enabled: false,
      order: 80,
      zone: 'main',
      maxItems: RESUME_LIMITS.referenceItems,
      fields: [
        { key: 'references.name', label: 'Name', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'references.title', label: 'Title', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'references.company', label: 'Company', type: 'text', enabled: true, maxLength: RESUME_LIMITS.shortText },
        { key: 'references.email', label: 'Email', type: 'email', enabled: true, maxLength: RESUME_LIMITS.email },
        { key: 'references.phone', label: 'Phone', type: 'phone', enabled: true, maxLength: RESUME_LIMITS.phone },
      ],
    },
  ],
};
