import { Transform, type TransformFnParams } from 'class-transformer';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUrl,
  IsUUID,
  MaxLength,
  MinLength,
} from 'class-validator';

import {
  AiContentReportFeatureType,
  AiContentReportIssue,
} from '../entities/ai-content-report.entity';

const trimValue = ({ value }: TransformFnParams): unknown => {
  return typeof value === 'string' ? value.trim() : value;
};

export class CreateAiContentReportDto {
  @IsEnum(AiContentReportFeatureType)
  featureType: AiContentReportFeatureType;

  @IsEnum(AiContentReportIssue)
  issue: AiContentReportIssue;

  @Transform(trimValue)
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  details?: string;

  /**
   * Session, conversation, generation, or other server/client source ID.
   */
  @Transform(trimValue)
  @IsOptional()
  @IsString()
  @MaxLength(160)
  sourceReference?: string;

  /**
   * The exact AI message or transcript ID when one exists.
   */
  @Transform(trimValue)
  @IsOptional()
  @IsString()
  @MaxLength(160)
  messageReference?: string;

  /**
   * Automatically supplied by the app. The user does not type this field.
   */
  @Transform(trimValue)
  @IsOptional()
  @IsString()
  @MinLength(1)
  @MaxLength(20000)
  aiContentText?: string;

  /**
   * Use this for a generated CV or other AI result already stored in files.
   */
  @IsOptional()
  @IsUUID()
  aiContentFileId?: string;

  /**
   * Fallback for AI output stored outside the files table.
   */
  @Transform(trimValue)
  @IsOptional()
  @IsUrl({
    protocols: ['http', 'https'],
    require_protocol: true,
  })
  @MaxLength(2000)
  aiContentUrl?: string;

  /**
   * Generated by the app so a retried request cannot create duplicates.
   */
  @Transform(trimValue)
  @IsOptional()
  @IsString()
  @MaxLength(120)
  clientReportId?: string;
}
